version: '3.8'

services:
  backend:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - OLLAMA_CLIENT_URL=http://host.docker.internal:11434
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: llm-backend
    ports:
      - '8000:8000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: llm-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
